routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('dashboard', 'DashboardController@index')->name('dashboard.index')->middleware(['auth']);

Route::group(['prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account', 'middleware' => 'auth'], function () {
    Route::get('/', 'AccountController@index')->name('index');

    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::post('profile', 'ProfileController@store')->name('profile.store');

    Route::get('password', 'PasswordController@index')->name('password.index');
    Route::post('password', 'PasswordController@store')->name('password.store');

    Route::get('deactivate', 'DeactivateController@index')->name('deactivate.index');
    Route::post('deactivate', 'DeactivateController@store')->name('deactivate.store');

    Route::group(['prefix' => 'files', 'as' => 'files.'], function () {
        Route::get('/', 'FileController@index')->name('index');
        Route::get('create', 'FileController@create')->name('create');
        Route::get('{file}/show', 'FileController@show')->name('show');
        Route::post('store', 'FileController@store')->name('store');
        Route::get('{file}/delete', 'FileController@destroy')->name('delete');
        Route::get('{upload}/download', 'FileController@getDownload')->name('download');
    });

    Route::group(['prefix' => 'subscription', 'namespace' => 'Subscription', 'as' => 'subscription.'], function () {
        Route::group(['middleware' => 'subscription.notcancelled'], function () {
            Route::get('cancel', 'SubscriptionCancelController@index')->name('cancel.index');
            Route::post('cancel', 'SubscriptionCancelController@store')->name('cancel.store');
        });

        Route::group(['middleware' => 'subscription.cancelled'], function () {
            Route::get('resume', 'SubscriptionResumeController@index')->name('resume.index');
            Route::post('resume', 'SubscriptionResumeController@store')->name('resume.store');
        });

        Route::group(['middleware' => 'subscription.customer'], function () {
            Route::get('card', 'SubscriptionCardController@index')->name('card.index');
            Route::post('card', 'SubscriptionCardController@store')->name('card.store');
        });
    });
});

Route::group(['prefix' => 'activation', 'as' => 'activation.', 'middleware' => ['guest'], 'namespace' => 'Auth'], function () {
    Route::get('/resend', 'ActivationResendController@index')->name('resend');
    Route::post('/resend', 'ActivationResendController@store')->name('resend.store');
    Route::get('/{confirmationToken}', 'ActivationController@activate')->name('activate')->middleware(['confirmation_token.expired:/']);
});

Route::group(['prefix' => 'plans', 'as' => 'plans.', 'namespace' => 'Subscription', 'middleware' => 'subscription.inactive'], function () {
    Route::get('/', 'PlanController@index')->name('index');
    Route::get('/teams', 'PlanTeamController@index')->name('teams.index');
});

Route::group(['prefix' => 'subscription', 'as' => 'subscription.', 'namespace' => 'Subscription', 'middleware' => ['auth.register', 'subscription.inactive']], function () {
    Route::get('/', 'SubscriptionController@index')->name('index');
    Route::post('/', 'SubscriptionController@store')->name('store');
});

app/Http/Controllers/Account/Subscription/SubscriptionCancelController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionCancelController extends Controller
{
    public function index()
    {
        return view('account.subscription.cancel.index');
    }

    public function store(Request $request)
    {
        $request->user()->subscription('main')->cancel();

        return redirect()->route('account.index')->with('success', 'Your subscription has been canceled.');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionCardController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionCardController extends Controller
{
    public function index()
    {
        return view('account.subscription.card.index');
    }

    public function store(Request $request)
    {
        $request->user()->updateCard($request->token);

        return redirect()->route('account.index')->with('success', 'Your card has been updated.');
    }
}

app/Http/Controllers/Account/Subscription/SubscriptionResumeController.php
<?php

namespace App\Http\Controllers\Account\Subscription;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubscriptionResumeController extends Controller
{
    public function index()
    {
        return view('account.subscription.resume.index');
    }

    public function store(Request $request)
    {
        $request->user()->subscription('main')->resume();

        return redirect()->route('account.index')->with('success', 'Your subscription has been resumed.');
    }
}

app/Http/Controllers/Subscription/PlanController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Models\Plan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PlanController extends Controller
{
    public function index()
    {
        $plans = Plan::active()->forUsers()->get();

        return view('subscription.plans.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/PlanTeamController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Models\Plan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PlanTeamController extends Controller
{
    public function index()
    {
        $plans = Plan::active()->forTeams()->get();

        return view('subscription.plans.teams.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/SubscriptionController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Http\Requests\Subscription\SubscriptionStoreRequest;
use App\Models\Plan;
use App\Http\Controllers\Controller;

class SubscriptionController extends Controller
{
    public function index()
    {
        $plans = Plan::active()->get();

        return view('subscription.index', compact('plans'));
    }

    public function store(SubscriptionStoreRequest $request)
    {
        $subscription = $request->user()->newSubscription('main', $request->plan);

        if ($request->has('coupon')) {
            $subscription->withCoupon($request->coupon);
        }

        $subscription->create($request->token);

        return redirect('/')->with('success', 'Thanks for becoming a subscriber!');
    }
}

resources/views/subscription/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Subscription</div>

                <div class="card-body">
                    <form action="{{ route('subscription.store') }}" method="POST" class="form-horizontal" id="payment-form">
                        @csrf

                        <div class="form-group">
                            <label for="plan" class="col-md-4 control-label">Plan</label>

                            <div class="col-md-12">
                                <select name="plan" id="plan" class="form-control{{ $errors->has('plan') ? ' is-invalid' : '' }}">
                                    @foreach ($plans as $plan)
                                        <option value="{{ $plan->gateway_id }}" {{ request('plan') === $plan->slug || old('plan') === $plan->gateway_id ? 'selected="selected"' : '' }}>{{ $plan->name }} (£{{ $plan->price }})</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('plan'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('plan') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="coupon" class="col-md-4 control-label">Coupon code</label>

                            <div class="col-md-12">
                                <input type="text" name="coupon" id="coupon" class="form-control{{ $errors->has('coupon') ? ' is-invalid' : '' }}" value="{{ old('coupon') }}">

                                @if ($errors->has('coupon'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('coupon') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary" id="pay">Pay</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <script>
        let handler = StripeCheckout.configure({
            key: '{{ config('services.stripe.key') }}',
            locale: 'auto',
            token: function (token) {
                let form = $('#payment-form')

                $('#pay').prop('disabled', true)

                $('<input>').attr({
                    type: 'hidden',
                    name: 'token',
                    value: token.id
                }).appendTo(form)

                form.submit();
            }
        })

        $(document).on('click','#pay',function(e){

            handler.open({
                name: 'Saas Ltd.',
                description: 'Membership',
                currency: 'gbp',
                key: '{{ config('services.stripe.key') }}',
                email: '{{ auth()->user()->email }}'
            })

            e.preventDefault();

        });

    </script>
@endsection